// Generated by jextract

package org.vybe.flecs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ecs_commands_t {
 *     ecs_vec_t queue;
 *     ecs_stack_t stack;
 *     ecs_sparse_t entries;
 * }
 * }
 */
public class ecs_commands_t {

    ecs_commands_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ecs_vec_t.layout().withName("queue"),
        ecs_stack_t.layout().withName("stack"),
        ecs_sparse_t.layout().withName("entries")
    ).withName("ecs_commands_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout queue$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("queue"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ecs_vec_t queue
     * }
     */
    public static final GroupLayout queue$layout() {
        return queue$LAYOUT;
    }

    private static final long queue$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ecs_vec_t queue
     * }
     */
    public static final long queue$offset() {
        return queue$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ecs_vec_t queue
     * }
     */
    public static MemorySegment queue(MemorySegment struct) {
        return struct.asSlice(queue$OFFSET, queue$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ecs_vec_t queue
     * }
     */
    public static void queue(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, queue$OFFSET, queue$LAYOUT.byteSize());
    }

    private static final GroupLayout stack$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stack"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ecs_stack_t stack
     * }
     */
    public static final GroupLayout stack$layout() {
        return stack$LAYOUT;
    }

    private static final long stack$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ecs_stack_t stack
     * }
     */
    public static final long stack$offset() {
        return stack$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ecs_stack_t stack
     * }
     */
    public static MemorySegment stack(MemorySegment struct) {
        return struct.asSlice(stack$OFFSET, stack$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ecs_stack_t stack
     * }
     */
    public static void stack(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stack$OFFSET, stack$LAYOUT.byteSize());
    }

    private static final GroupLayout entries$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("entries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ecs_sparse_t entries
     * }
     */
    public static final GroupLayout entries$layout() {
        return entries$LAYOUT;
    }

    private static final long entries$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ecs_sparse_t entries
     * }
     */
    public static final long entries$offset() {
        return entries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ecs_sparse_t entries
     * }
     */
    public static MemorySegment entries(MemorySegment struct) {
        return struct.asSlice(entries$OFFSET, entries$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ecs_sparse_t entries
     * }
     */
    public static void entries(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, entries$OFFSET, entries$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

