// Generated by jextract

package org.vybe.flecs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ecs_query_count_t {
 *     int32_t results;
 *     int32_t entities;
 *     int32_t tables;
 *     int32_t empty_tables;
 * }
 * }
 */
public class ecs_query_count_t {

    ecs_query_count_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        flecs.C_INT.withName("results"),
        flecs.C_INT.withName("entities"),
        flecs.C_INT.withName("tables"),
        flecs.C_INT.withName("empty_tables")
    ).withName("ecs_query_count_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt results$LAYOUT = (OfInt)$LAYOUT.select(groupElement("results"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t results
     * }
     */
    public static final OfInt results$layout() {
        return results$LAYOUT;
    }

    private static final long results$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t results
     * }
     */
    public static final long results$offset() {
        return results$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t results
     * }
     */
    public static int results(MemorySegment struct) {
        return struct.get(results$LAYOUT, results$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t results
     * }
     */
    public static void results(MemorySegment struct, int fieldValue) {
        struct.set(results$LAYOUT, results$OFFSET, fieldValue);
    }

    private static final OfInt entities$LAYOUT = (OfInt)$LAYOUT.select(groupElement("entities"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t entities
     * }
     */
    public static final OfInt entities$layout() {
        return entities$LAYOUT;
    }

    private static final long entities$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t entities
     * }
     */
    public static final long entities$offset() {
        return entities$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t entities
     * }
     */
    public static int entities(MemorySegment struct) {
        return struct.get(entities$LAYOUT, entities$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t entities
     * }
     */
    public static void entities(MemorySegment struct, int fieldValue) {
        struct.set(entities$LAYOUT, entities$OFFSET, fieldValue);
    }

    private static final OfInt tables$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tables"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t tables
     * }
     */
    public static final OfInt tables$layout() {
        return tables$LAYOUT;
    }

    private static final long tables$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t tables
     * }
     */
    public static final long tables$offset() {
        return tables$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t tables
     * }
     */
    public static int tables(MemorySegment struct) {
        return struct.get(tables$LAYOUT, tables$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t tables
     * }
     */
    public static void tables(MemorySegment struct, int fieldValue) {
        struct.set(tables$LAYOUT, tables$OFFSET, fieldValue);
    }

    private static final OfInt empty_tables$LAYOUT = (OfInt)$LAYOUT.select(groupElement("empty_tables"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t empty_tables
     * }
     */
    public static final OfInt empty_tables$layout() {
        return empty_tables$LAYOUT;
    }

    private static final long empty_tables$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t empty_tables
     * }
     */
    public static final long empty_tables$offset() {
        return empty_tables$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t empty_tables
     * }
     */
    public static int empty_tables(MemorySegment struct) {
        return struct.get(empty_tables$LAYOUT, empty_tables$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t empty_tables
     * }
     */
    public static void empty_tables(MemorySegment struct, int fieldValue) {
        struct.set(empty_tables$LAYOUT, empty_tables$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

