# Project info
site_name: Vybe
site_url: https://vybegame.dev/vybe/
site_author: Paulo Feodrippe
site_description: >-
  A Clojure Game Framework

# Repo
repo_name: Vybe
repo_url: https://github.com/pfeodrippe/vybe
edit_uri: edit/main/docs/

# Theme
theme:
  font:
    text: Roboto Slab
    code: Roboto Mono

  features:
    # Navigation
    - navigation.tabs
    - navigation.sections

    # Can edit a page, view the source
    - content.action.edit
    - content.action.view

    # Code highlighting
    - content.code.copy

    # Expand all subsections by default
    # - navigation.expand

  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # custom_dir: overrides

# Extensions
markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Footnotes
  - footnotes

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets

  # Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


# Pages
nav:
  - Home:
    - index.md
    - Requirements: requirements.md
  - Vybe Game Framework:
    - Getting Started: getting-started.md
  - VybeC:
    - vybec/index.md
